apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devagent-hpa
  namespace: devagent-poc
  labels:
    app.kubernetes.io/name: devagent
    app.kubernetes.io/component: hpa
    app.kubernetes.io/part-of: saas-factory
  annotations:
    description: "DevAgent Horizontal Pod Autoscaler for K8s POC"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devagent
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics (if available)
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
# Vertical Pod Autoscaler (optional, for GKE Autopilot)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: devagent-vpa
  namespace: devagent-poc
  labels:
    app.kubernetes.io/name: devagent
    app.kubernetes.io/component: vpa
    app.kubernetes.io/part-of: saas-factory
  annotations:
    description: "DevAgent Vertical Pod Autoscaler for resource optimization"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devagent
  updatePolicy:
    updateMode: "Auto"  # Can be "Off", "Initial", or "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: devagent
      maxAllowed:
        cpu: "2"
        memory: "4Gi"
      minAllowed:
        cpu: "100m"
        memory: "256Mi"
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
    - containerName: metrics-exporter
      mode: "Off"  # Don't auto-scale the sidecar 