project_id            = "summer-nexus-463503-e1"
region                = "us-central1"
owner_email           = "n2nstreams@gmail.com"
devops_group          = "devops-saas-factory@example.com"
viewer_group          = "viewers-saas-factory@example.com"
db_password           = "changeMe-9viY2!"
billing_account       = "YOUR_BILLING_ACCOUNT_ID"
slack_webhook_token   = "YOUR_SLACK_WEBHOOK_TOKEN" 