name: CI - Python

on:
  pull_request:
    paths:
      - '**/*.py'
      - 'requirements*.txt'
      - 'pytest.ini'
      - 'tests/**'
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-base.txt
          if [ -f requirements-agents.txt ]; then pip install -r requirements-agents.txt; fi
          if [ -f orchestrator/requirements.txt ]; then pip install -r orchestrator/requirements.txt; fi
          if [ -f api-gateway/requirements.txt ]; then pip install -r api-gateway/requirements.txt; fi
      - name: Lint (ruff optional)
        run: |
          echo "Skipping ruff; add when ready"
      - name: Run tests
        run: |
          pytest -q


