name: CI - Python

on:
  pull_request:
    paths:
      - '**/*.py'
      - 'requirements*.txt'
      - 'pytest.ini'
      - 'tests/**'
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: test
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: factorydb
      DB_USER: factoryadmin
      DB_PASSWORD: localpass
      SECRET_MANAGER_ENABLED: "false"
      MONITORING_ENABLED: "false"
      OPENAI_API_KEY: test-key
      JWT_SECRET_KEY: test-jwt
    services:
      postgres:
        image: pgvector/pgvector:pg15
        env:
          POSTGRES_USER: factoryadmin
          POSTGRES_PASSWORD: localpass
          POSTGRES_DB: factorydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U factoryadmin" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-base.txt
          if [ -f requirements-agents.txt ]; then pip install -r requirements-agents.txt; fi
          if [ -f orchestrator/requirements-orchestrator.txt ]; then pip install -r orchestrator/requirements-orchestrator.txt; fi
          if [ -f api_gateway/requirements.txt ]; then pip install -r api_gateway/requirements.txt; fi
          
      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U factoryadmin && break
            sleep 2
          done
          
      - name: Create pgvector extension
        env:
          PGPASSWORD: localpass
        run: |
          psql -h localhost -U factoryadmin -d factorydb -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
          psql -h localhost -U factoryadmin -d factorydb -c 'CREATE EXTENSION IF NOT EXISTS vector;'
          
      - name: Initialize database schema
        env:
          PGPASSWORD: localpass
        run: |
          if [ -f dev/init.sql ]; then
            psql -h localhost -U factoryadmin -d factorydb -f dev/init.sql
          fi
          if [ -d dev/migrations ]; then
            for f in dev/migrations/*.sql; do 
              if [ -f "$f" ]; then
                echo "Running migration: $f"
                psql -h localhost -U factoryadmin -d factorydb -f "$f"
              fi
            done
          fi
          
      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check --select=E9,F63,F7,F82 --statistics . || true
          ruff check --exit-zero --statistics .
          
      - name: Run tests
        run: |
          # Check for test files and run them
          TEST_FILES=$(find . -name "*test*.py" -o -name "test_*.py" 2>/dev/null | grep -v -E "(\.venv|venv|env|y/google-cloud-sdk|orchestrator/\.venv)" | head -1)
          if [ -n "$TEST_FILES" ]; then
            echo "Test files found, running pytest..."
            pytest -q --tb=short -v
          else
            echo "No test files found, creating dummy coverage"
            mkdir -p .
            echo '<?xml version="1.0" ?><coverage version="7.0.0"><sources></sources><packages></packages></coverage>' > ./coverage.xml
          fi


