name: Security - Container Scan

on:
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/docker-compose*.yml'
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Find Dockerfiles
        id: find-dockerfiles
        run: |
          DOCKERFILES=$(find . -name "Dockerfile" -type f | head -10)
          if [ -n "$DOCKERFILES" ]; then
            echo "Found Dockerfiles:"
            echo "$DOCKERFILES"
            echo "dockerfiles=$DOCKERFILES" >> $GITHUB_OUTPUT
          else
            echo "No Dockerfiles found"
            echo "dockerfiles=" >> $GITHUB_OUTPUT
          fi
          
      - name: Trivy filesystem scan
        if: steps.find-dockerfiles.outputs.dockerfiles != ''
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          hide-progress: true
          scan-ref: '.'
          
      - name: Skip scan if no Dockerfiles
        if: steps.find-dockerfiles.outputs.dockerfiles == ''
        run: |
          echo "No Dockerfiles found, skipping container scan"
          echo "This is expected for projects without containerization"
          
      - name: Upload scan results
        if: always() && steps.find-dockerfiles.outputs.dockerfiles != ''
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.json
          retention-days: 30


