name: Security - Container Scan

on:
  pull_request:
    paths:
      - '**/Dockerfile'
  schedule:
    - cron: '0 6 * * 1'

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          hide-progress: true


