name: Smoke Tests - Critical Path

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Run daily at 2 AM UTC to catch issues early
  schedule:
    - cron: '0 2 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  marketplace-signup-smoke:
    runs-on: ubuntu-latest
    name: Marketplace Signup Smoke Tests
    timeout-minutes: 15
    
    services:
      postgres:
        image: pgvector/pgvector:pg15
        env:
          POSTGRES_DB: factorydb
          POSTGRES_USER: factoryadmin
          POSTGRES_PASSWORD: localpass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-smoke-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-smoke-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install core dependencies for smoke tests
          pip install pytest pytest-asyncio pytest-mock httpx
          pip install fastapi uvicorn pydantic==2.10.5 pydantic-settings==2.7.0 sqlalchemy asyncpg
          pip install bcrypt python-dotenv
          
          # Install project dependencies if they exist
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f api-gateway/requirements.txt ]; then pip install -r api-gateway/requirements.txt; fi
          
      - name: Set up database schema
        run: |
          # Wait for postgres to be ready
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done
          
          # Apply database migrations for smoke tests
          if [ -d "dev/migrations" ]; then
            echo "Applying database migrations..."
            for migration in dev/migrations/*.sql; do
              if [ -f "$migration" ]; then
                echo "Applying $(basename $migration)..."
                PGPASSWORD=localpass psql -h localhost -U factoryadmin -d factorydb -f "$migration" || echo "Migration $(basename $migration) skipped (may already be applied)"
              fi
            done
          fi
          
      - name: Run marketplace signup smoke tests
        run: |
          echo "🚀 Running marketplace signup smoke tests..."
          
          # Run the specific smoke test file with verbose output
          python -m pytest tests/integration/test_marketplace_signup_smoke.py \
            -v \
            --tb=short \
            --durations=10 \
            --timeout=300 \
            -x \
            --disable-warnings
            
        env:
          DATABASE_URL: postgresql://factoryadmin:localpass@localhost:5432/factorydb
          DB_HOST: localhost
          DB_USER: factoryadmin
          DB_PASS: localpass
          DB_NAME: factorydb
          DB_PORT: 5432
          ENVIRONMENT: test
          DEBUG: true
          # Mock external services for smoke tests
          MOCK_EMAIL_SERVICE: true
          MOCK_STRIPE_SERVICE: true
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results
          path: |
            pytest.log
            test-reports/
          retention-days: 7
          
      - name: Report test status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ All smoke tests passed! Marketplace signup flow is healthy."
          else
            echo "❌ Smoke tests failed! Critical marketplace functionality may be broken."
            echo "🔍 Check the test results for details on what failed."
          fi

  # Quick API health check
  api-health-check:
    runs-on: ubuntu-latest
    name: API Health Check
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn httpx pytest
          pip install asyncpg bcrypt pydantic==2.10.5 pydantic-settings==2.7.0 sqlalchemy python-dotenv
          
      - name: Quick API structure validation
        run: |
          echo "🔍 Validating API structure..."
          
          # Check that API routes exist and can be imported
          python -c "
          import sys
          import os
          sys.path.append('api-gateway')
          # Add the current directory to PYTHONPATH for local imports
          os.environ['PYTHONPATH'] = 'api-gateway:' + os.environ.get('PYTHONPATH', '')
          try:
              from user_routes import router
              print('✅ User routes imported successfully')
              
              # Check for critical endpoints
              routes = [route.path for route in router.routes]
              critical_endpoints = ['/api/users/register', '/api/users/login', '/api/users/profile']
              
              for endpoint in critical_endpoints:
                  if any(endpoint in route for route in routes):
                      print(f'✅ Found critical endpoint: {endpoint}')
                  else:
                      print(f'❌ Missing critical endpoint: {endpoint}')
                      sys.exit(1)
                      
              print('🎉 All critical API endpoints are present')
              
          except ImportError as e:
              print(f'❌ Failed to import API routes: {e}')
              sys.exit(1)
          "
          
      - name: Validate frontend signup form
        run: |
          echo "🔍 Validating frontend signup form..."
          
          # Check that signup form exists and has required fields
          if [ -f "ui/src/pages/Signup.tsx" ]; then
            echo "✅ Signup page exists"
            
            # Check for critical form fields
            required_fields=("firstName" "lastName" "email" "password" "confirmPassword" "agreeToTerms")
            
            for field in "${required_fields[@]}"; do
              if grep -q "$field" ui/src/pages/Signup.tsx; then
                echo "✅ Found required field: $field"
              else
                echo "❌ Missing required field: $field"
                exit 1
              fi
            done
            
            echo "🎉 All required form fields are present"
          else
            echo "❌ Signup page not found!"
            exit 1
          fi

  # Report overall smoke test status
  smoke-test-summary:
    runs-on: ubuntu-latest
    needs: [marketplace-signup-smoke, api-health-check]
    if: always()
    
    steps:
      - name: Report overall status
        run: |
          SIGNUP_STATUS="${{ needs.marketplace-signup-smoke.result }}"
          API_STATUS="${{ needs.api-health-check.result }}"
          
          echo "📊 Smoke Test Summary:"
          echo "  Marketplace Signup: $SIGNUP_STATUS"
          echo "  API Health Check: $API_STATUS"
          
          if [ "$SIGNUP_STATUS" == "success" ] && [ "$API_STATUS" == "success" ]; then
            echo "✅ All smoke tests passed! System is ready for deployment."
            exit 0
          else
            echo "❌ Some smoke tests failed! Review before deploying."
            exit 1
          fi 